- type: job
  id: Lawyer
  name: Юрист
  description: Охраняйте честь и достоинство экипажа на допросах, помогайте составлять документ на выдачу диска ядерной аутентификации пассажиру станции и проводите юридические консультации по запросу сотрудников станции.
  playTimeTracker: JobLawyer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 9000 # 2.5 hrs
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: Агенту Внутренних Дел и Магистрату
  access:
  - Lawyer
  - Brig
  - Maintenance

- type: startingGear
  id: LawyerGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetLaw
  inhand:
    - BriefcaseBrownFilled
  storage:
    back:
    - RubberStampLawyer
    - BookSpaceLaw

- type: chameleonOutfit
  id: LawyerChameleonOutfit
  job: Lawyer
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckLawyerbadge
    outerClothing: ClothingOuterWinterColorBlack
    gloves: ClothingHandsGlovesColorBlack
