- type: job
  id: SecuritySapper
  name: Сапёр
  description: На постоянной основе носите костюм сапёра и обезвреживайте учебные бомбы. В случае высокой загруженности отдела выполняйте обязанности Офицера СБ.
  playTimeTracker: JobSecuritySapper
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 #10 hrs
  weight: 3
  startingGear: SecuritySapperGear
  icon: "JobIconSecuritySapper"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SecuritySapperGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSapper
    pocket1: WeaponPistolMk58
    jumpsuit: ClothingUniformJumpsuitSapper
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsJackFilled
    id: SapperPDA

  storage:
    back:
    - Flash
    - MagazinePistol
    - HoloprojectorSapper
    - ClothingOuterSuitBomb
    - ClothingHeadHelmetBombSuit
    - RubberStampSapper
